Vinicius validacao form
arthurbarbero/DB-LGPD pull request #23
Opened 2020-10-15 12:56 UTC by JViniciusF

Foram criadas validações simples de campo , validando somente os valores dos campos , e transmitindo alertas visuais aos usuarios

2020-10-15 13:13 UTC, arthurbarbero requested changes
Não fica bravo comigo, to ensinando padrão de código apenas, os espaços são importantes em todas as empresas que eu passei, ja tomei xingo por isso.

Tirando isso só aquele onFocusLoose que eu acho que teria que repensar a forma do hasclass la

2020-10-15 13:13 UTC, arthurbarbero commented on front-end/javaScript/signup.js
> +    let hasclass = element.classList
Esse hasClass sempre terá um ClassList, não seria melhor tu procurar pelo class específico (span)?

2020-10-15 13:13 UTC, arthurbarbero commented on front-end/javaScript/signup.js
>  }
Coloca um espaço entre as funções de uma linha

2020-10-15 13:13 UTC, arthurbarbero commented on front-end/javaScript/signup.js
> +async function onFocusLoose(element) {
Coloca um espaço entre as funções de uma linha

2020-10-15 13:13 UTC, arthurbarbero commented on front-end/javaScript/signup.js
> +
Remove esses dois espaços novos, deve ficar apenas com 1 espaço.

2020-10-15 13:13 UTC, arthurbarbero commented on front-end/template/signup-page.html
> +
HTML não tem espaço, só indentação

2020-10-15 13:13 UTC, arthurbarbero commented on front-end/template/signup-page.html
> +
HTML não tem espaço, só indentação

2020-10-15 13:13 UTC, arthurbarbero commented on front-end/template/signup-page.html
> +
HTML não tem espaço, só indentação

2020-10-15 13:13 UTC, arthurbarbero commented on front-end/template/signup-page.html
> +
HTML não tem espaço, só indentação

2020-10-15 13:13 UTC, arthurbarbero commented on front-end/template/signup-page.html
> +
HTML não tem espaço, só indentação

2020-10-15 14:32 UTC, JViniciusF commented
Ajustes concluidos , commit na branch ok , falta revisao

2020-10-15 15:12 UTC, arthurbarbero requested changes
Faltou uns espaços

2020-10-15 15:12 UTC, arthurbarbero commented on front-end/javaScript/signup.js
>  }
Ainda falta espaço aqui

2020-10-15 15:12 UTC, arthurbarbero commented on front-end/javaScript/signup.js
> +async function onFocusLoose(element) {
Ainda falta um espaço aqui

2020-10-16 11:58 UTC, arthurbarbero requested changes

2020-10-16 11:58 UTC, arthurbarbero commented on front-end/javaScript/signup.js
> +async function onFocusLoose(element) {
Carai José, entre as linhas 66 e 67

2020-10-16 11:58 UTC, arthurbarbero commented on front-end/javaScript/signup.js
>  }
poha bixo, entre as linhas 59 e 60

2020-10-16 12:19 UTC, arthurbarbero approved these changes

2020-10-16 12:19 UTC, merged